### ISSUE TITLE
1 fout in 5.2 en 1 fout in 5.3 - normal forms

### ISSUE THREAD

**Issue by KayRensen** [jkorb/logicalmethods.ai#10]
1) fout in 5.2

![image](https://github.com/user-attachments/assets/e84c8908-91d3-4c31-b330-c7183054f5a7)

Aan de rechterkant komen 2 negatie tekens en die zouden dan wegvallen. 

2) fout in 5.3
![image](https://github.com/user-attachments/assets/c3df4a72-6a7e-4a6e-874e-6a4a2c89fb6b)

Hier moet ν1 (RAIN∨BIKE) = 1 zijn i.p.v. 0

**Comment by jkorb** [comment]
Thanks, @KayRensen !
