### ISSUE TITLE
Truth-tables for the conditional operator in 3-valued setting seem to be incorrect. 

### ISSUE THREAD

**Issue by BKBKlaassen** [jkorb/logicalmethods.ai#16]
Unless I am missing something the following three images are incorrect:

![cond_luk](https://github.com/user-attachments/assets/cd2e6c46-17b6-45cd-aa7b-e5d79f95e019)
![cond_kleene](https://github.com/user-attachments/assets/0d5bbba4-a3b3-43c6-a872-2f7dea58d93f)
![cond_question](https://github.com/user-attachments/assets/391f1b17-0cbb-4e1e-adb2-3f63e5a31f23)

In the case of 1 -> 0, shouldn't the outcome be 0 and not 1?

**Comment by jkorb** [comment]
Absolutely correct, will be fixed in a second. Thanks @BKBKlaassen !
