### ISSUE TITLE
Minor mistake tutorial 3

### ISSUE THREAD

**Issue by Jivvels** [jkorb/logicalmethods.ai#5]
In question 2a, it's missing one  closing parentheses ")" at the end. There's more opening parentheses "(" than closing parentheses ")"

(SHUT_DOWN↔((REQUEST_REPAIR∧¬REPAIR)∨(INSPECT_SENSORS∧FAULTY))

Should be 

(SHUT_DOWN↔((REQUEST_REPAIR∧¬REPAIR)∨(INSPECT_SENSORS∧FAULTY)))

**Comment by jkorb** [comment]
Nice, great spot @Jivvels ! Thanks :)
